# Generated by Django 4.2.4 on 2024-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testProject', '0002_alter_csvdata_end_date_alter_csvdata_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='category',
            field=models.IntegerField(),
        ),
    ]
